language: python
os: linux
dist: precise
python:
  - 2.7
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libav-tools libi2c-dev python-numpy python-setuptools python-smbus
  - git clone git://git.drogon.net/wiringPi && cd ./wiringPi && ./build && cd ..
  - wget abyz.co.uk/rpi/pigpio/pigpio.zip && unzip pigpio.zip && cd ./PIGPIO && make -j4 && sudo make install && cd ..
  - pip install --upgrade pip webtest
  - wget https://dl.influxdata.com/influxdb/releases/influxdb_1.1.1_amd64.deb && sudo dpkg -i influxdb_1.1.1_amd64.deb
  - sudo service influxdb start
  - influx -execute "CREATE DATABASE mycodo_db"
  - influx -database mycodo_db -execute "CREATE USER mycodo WITH PASSWORD 'mmdu77sj3nIoiajjs'"
install:
  - pip install --upgrade -r install/requirements.txt
virtualenv:
    system_site_packages: true
script:
  - cd mycodo && python -m pytest tests/software_tests -s